---
# tasks file for ec2Instance_launch
- name: Launching 3 instances
  ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: true
      region: "{{ region }}"
      vpc_subnet_id: subnet-46a2dc0a
      assign_public_ip: yes
      instance_tags:
          node: "{{ item }}"
  register: ec2
  loop: "{{tags}}"
           
